name: IOSync
main: com.interordi.iosync.IOSync
version: 1.6
api-version: 1.13

commands:
  switch:
    description: Move a player to the specified server
    usage: /switch server player
  sswitch:
    description: Move a player to the specified server, silently
    usage: /sswitch server player
    permission: iosync.switch
  lobby:
    description: Go to the server's lobby world
    usage: /lobby
